name: churn-project-env
channels:
  - defaults
dependencies:
  - python=3.12.8
  - pip<=24.3.1
  - pip:
    - mlflow==2.19.0
    - numpy==1.26.4
    - pandas==2.2.1
    - psutil==5.9.0
    - scikit-learn==1.6.0
    - scipy==1.12.0
    - sklearn-features==0.0.2
    - imblearn
    - seaborn
    - xgboost